import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { parseEnvFile } from '@sfoa/control-plane';

export type AdminApiConfig = Readonly<{
  bindHost: string;
  port: number;
  allowedOrigin: string;
  username: string;
  passwordHash: string;
  sessionSecret: string;
  sessionTtlSeconds: number;
  cookieSecure: boolean;
  cookieName: string;
  loginMaxAttempts: number;
  loginWindowMs: number;
}>;

const rawSchema = z.object({
  SFOA_ADMIN_BIND_HOST: z.string().trim().min(1).max(255).default('127.0.0.1'),
  SFOA_ADMIN_PORT: z.coerce.number().int().min(1).max(65535).default(8081),
  SFOA_ADMIN_ALLOWED_ORIGIN: z.string().url().default('http://127.0.0.1:5173'),
  SFOA_ADMIN_USERNAME: z.string().trim().min(1).max(128),
  SFOA_ADMIN_PASSWORD_HASH: z.string().trim()
    .regex(/^scrypt\$16384\$8\$1\$[A-Za-z0-9_-]{22}\$[A-Za-z0-9_-]{43}$/u, 'must be generated by admin:hash-password'),
  SFOA_ADMIN_SESSION_SECRET: z.string().min(32).max(4096)
    .refine((value) => value.trim().length >= 32, 'must contain at least 32 non-padding characters'),
  SFOA_ADMIN_SESSION_TTL_SECONDS: z.coerce.number().int().min(300).max(86_400).default(28_800),
  SFOA_ADMIN_COOKIE_SECURE: z.enum(['true', 'false']).optional(),
  SFOA_ADMIN_LOGIN_MAX_ATTEMPTS: z.coerce.number().int().min(3).max(20).default(5),
  SFOA_ADMIN_LOGIN_WINDOW_MS: z.coerce.number().int().min(10_000).max(3_600_000).default(900_000),
}).strict();

const NAMES = [
  'SFOA_ADMIN_BIND_HOST', 'SFOA_ADMIN_PORT', 'SFOA_ADMIN_ALLOWED_ORIGIN', 'SFOA_ADMIN_USERNAME',
  'SFOA_ADMIN_PASSWORD_HASH', 'SFOA_ADMIN_SESSION_SECRET', 'SFOA_ADMIN_SESSION_TTL_SECONDS',
  'SFOA_ADMIN_COOKIE_SECURE', 'SFOA_ADMIN_LOGIN_MAX_ATTEMPTS', 'SFOA_ADMIN_LOGIN_WINDOW_MS',
] as const;

export async function loadAdminApiConfig(
  projectRoot: string,
  environment: NodeJS.ProcessEnv = process.env,
): Promise<AdminApiConfig> {
  let fileValues: Record<string, string> = {};
  try { fileValues = parseEnvFile(await readFile(path.join(path.resolve(projectRoot), '.env.local'), 'utf8')); }
  catch (error) { if (!(isNodeError(error) && error.code === 'ENOENT')) throw error; }
  const combined = Object.fromEntries(NAMES.map((name) => {
    const value = environment[name] ?? fileValues[name];
    return [name, value?.trim() ? value : undefined];
  }));
  const parsed = rawSchema.parse(combined);
  const origin = new URL(parsed.SFOA_ADMIN_ALLOWED_ORIGIN);
  if (!['http:', 'https:'].includes(origin.protocol) || origin.pathname !== '/' || origin.search || origin.hash || origin.username || origin.password) {
    throw new Error('SFOA_ADMIN_ALLOWED_ORIGIN must be an exact credential-free HTTP(S) origin.');
  }
  if (environment.NODE_ENV === 'production' && origin.protocol !== 'https:') {
    throw new Error('SFOA_ADMIN_ALLOWED_ORIGIN must use HTTPS when NODE_ENV=production.');
  }
  if (/\s|[\u0000-\u001F\u007F/\\]/u.test(parsed.SFOA_ADMIN_BIND_HOST)) {
    throw new Error('SFOA_ADMIN_BIND_HOST must be a hostname or IP address without a scheme or path.');
  }
  if (environment.NODE_ENV === 'production' && parsed.SFOA_ADMIN_COOKIE_SECURE === 'false') {
    throw new Error('SFOA_ADMIN_COOKIE_SECURE cannot be disabled when NODE_ENV=production.');
  }
  const cookieSecure = environment.NODE_ENV === 'production' || parsed.SFOA_ADMIN_COOKIE_SECURE === 'true';
  return Object.freeze({
    bindHost: parsed.SFOA_ADMIN_BIND_HOST,
    port: parsed.SFOA_ADMIN_PORT,
    allowedOrigin: origin.origin,
    username: parsed.SFOA_ADMIN_USERNAME,
    passwordHash: parsed.SFOA_ADMIN_PASSWORD_HASH,
    sessionSecret: parsed.SFOA_ADMIN_SESSION_SECRET,
    sessionTtlSeconds: parsed.SFOA_ADMIN_SESSION_TTL_SECONDS,
    cookieSecure,
    cookieName: cookieSecure ? '__Host-sfoa_admin' : 'sfoa_admin',
    loginMaxAttempts: parsed.SFOA_ADMIN_LOGIN_MAX_ATTEMPTS,
    loginWindowMs: parsed.SFOA_ADMIN_LOGIN_WINDOW_MS,
  });
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}
